version: '3.2'
services:
  backend:
    build: .
    ports:
      - 80:3000
    depends_on:
      - db
    volumes:
      - .:/home/node/LetsTripWeb
    restart: always
    links:
      - db

    # build:
    #   context: .
    #   dockerfile: Dockerfile

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
       - 3307:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: letstrip_phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    links:
      - db
